<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProyectoProgramacion3DBManager\ProyectoProgramacion3DBManager.csproj" />
    <ProjectReference Include="..\ProyectoProgramacion3Negocio\ProyectoProgramacion3Negocio.csproj" />
  </ItemGroup>

</Project>
